export interface UserModel {
  nombre: string,
  primer_apellido: string,
  segundo_apellido: string,
  dni: string,
  fecha_nacimiento: string,
  email: string,
  password: string,
  tipo_via: string,
  nombre_via: string,
  numero: string,
  piso: string,
  puerta: string,
  province: string,
  municipio: string,
  tel_fijo: string,
  tel_movil: string,
  codigo_postal:string,
  // id?:number,
  // rol_id?:number,
  // nombre_rol?:string,
  // num_historia_clinica?:string,
  // provincia_id?:number
}
